
#[derive(Debug, Clone, Serialize)]
pub struct CardTokenized {
    /// Token generated by vault or HSM
    pub card_token: String,

    /// BIN (6-8 first digits)
    pub bin: String,

    /// Last 4 digits
    pub last4: String,

    /// Expiration
    pub exp_month: u8,
    pub exp_year: u16,

    /// Card scheme: VISA, MASTERCARD, JCB...
    pub scheme: CardScheme,
}

impl CardTokenized {
    fn new(
        card_token: String,
        bin: String,
        last4: String,
        exp_month: u8,
        exp_year: u16
    ) -> Result<Self, CardErr> {
        if last4.len() != 4 {
            return Err(CardErr)
        }
    }
}
